[package]
name = "dogecoincore-rpc-json"
version = "0.19.0"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>"
]
license = "CC0-1.0"
homepage = "https://github.com/dfinity/rust-dogecoincore-rpc/"
repository = "https://github.com/dfinity/rust-dogecoincore-rpc/"
description = "JSON-enabled type structs for dogecoincore-rpc crate."
keywords = [ "crypto", "dogecoin", "dogecoin-core", "rpc" ]
readme = "README.md"
edition = "2021"

[lib]
name = "dogecoincore_rpc_json"
path = "src/lib.rs"

[features]
default = [ "rand" ]
rand = ["bitcoin/rand-std"]

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"

bitcoin = { git = "https://github.com/dfinity/rust-dogecoin", rev = "b5125f00d9d1e6c553d83ee54ee9d6203da8e0db", features = [ "serde" ]}
